### ISSUE TITLE
Move libIME to a submodule.

### ISSUE THREAD

**Issue by PCMan** [chewing/windows-chewing-tsf#124]
PIME and windows-chewing-tsf both use libIME.
I already split libIME into its own repository.
https://github.com/EasyIME/libIME
It's better to use libIME in windows-chewing-tsf as a submodule for better maintenance.

**Comment by Chocobo1** [comment]
@PCMan 
Minor thing, commit dd9293c99a6c1cb317194a9a86955cd7f8eab218 wasn't included in EasyIME/libIME, It will be best if you can pick it into the new repo. So the libIME here can be replaced without any loss.

**Comment by PCMan** [comment]
@Chocobo1 Thanks for the reminder.
Are you interested in helping this part and creating a PR for it? :)

**Comment by Chocobo1** [comment]
>Are you interested in helping this part and creating a PR for it? :)

No problem.
Opened PR: https://github.com/EasyIME/libIME/pull/1

**Comment by Chocobo1** [comment]
I opened another PR for this issue: https://github.com/chewing/windows-chewing-tsf/pull/125
