### ISSUE TITLE
2016.05.11 windows-chewing-tsf.exe 被防毒軟體判定含有惡意軟體

### ISSUE THREAD

**Issue by joehuang0001** [chewing/windows-chewing-tsf#131]
我用Comodo的 Internet Security, 下載 2016.05.11 windows-chewing-tsf.exe 後，該檔案被立刻自動刪除，檢查病毒隔離區發現被判定含有TrojWare.Win32.Kryptik.CGL，用手機下載該檔案上傳virustotal進行掃描結果54個防毒軟體有4判定含有惡意軟體。2016.03.18的windows-chewing-tsf.exe沒有這樣的問題。

**Comment by kanru** [comment]
24.10 會提供數位簽章，應該可避免被判斷為惡意程式
