### ISSUE TITLE
Windows 7 X64 CMD Console 無法輸入中文

### ISSUE THREAD

**Issue by peter8777555** [chewing/windows-chewing-tsf#136]
Bug:
Windows 7 X64 CMD Console 無法輸入中文,
謝謝.

**Comment by osk2** [comment]
Possible duplicate of #122

**Comment by peter8777555** [comment]
這則我有看到(看圖應該是 Windows 8/8.1/10),
但不一樣.

我昨天在 Windows 10 X64 CMD Console 中新酷音可以輸入中文,
但是 Windows 7 X64 CMD Console 無法輸入中文.

**Comment by peter8777555** [comment]
>Possible duplicate of #122
看了 Microsoft Windows [版本 6.1.7601]
確實是 Windows 7,
問題是一樣.

我昨天在 Windows 10 X64 CMD Console 中新酷音已可以輸入中文,
但是 Windows 7 X64 CMD Console 無法輸入中文.

**Comment by peter8777555** [comment]
Windows 7 X64 CMD Console 無法輸入中文 ,
這麼多年了 還沒有修護 ?

**Comment by kanru** [comment]
看起來 v24.10 已修復

**Comment by peter8777555** [comment]
我已升到 Windows 11,
所以 無法測試 Windows 7.
