### ISSUE TITLE
能一個字一個字輸入嗎(不要自動判斷字詞) ?

### ISSUE THREAD

**Issue by peter8777555** [chewing/windows-chewing-tsf#137]
對於使用電腦超過 20 年以上,
使用中文輸入的"習慣"已很難更改,
 希望貴輸入法能幫助老使用者.

在 Windows XP/7 中的ㄅ半注音輸入時,
注音打一個字,選字,就 OK 了.

但新酷音跟微軟新注音一樣都會在字的下方有一虛線,會自動判斷字詞,
能加一設定關閉此功能嗎 ?
!! 不要自動判斷字詞,能一個字一個字輸入(自選字) !!

例: 打 "機"
Windows XP/7 中的ㄅ半注音輸入 : ㄐ一 空白鍵 1
新酷音注音輸入 : ㄐ一 空白鍵 空白鍵 1

新酷音注音輸入要按兩次空白鍵,
這應該是要等待判斷字詞.
(PS:我有打勾"按空白鍵叫出選字視窗")

謝謝.

**Comment by kanru** [comment]
同 #139
