### ISSUE TITLE
建請新增設定：輸入每字後自動叫出選字框

### ISSUE THREAD

**Issue by Aukwang** [chewing/windows-chewing-tsf#139]
由於用了二十幾年的ㄅ半傳統注音，現在面臨win10，所有傳統注音的解決方式都半殘，win10底下許多如apps或EDGE都不能使用，試用了許多方法只剩新酷音最能夠符合需求

現在的新酷音既然已能夠空白鍵選字，能否加入新的設定(ex. checkbox)，讓需要的人選擇，每次輸入一個字時自動跳出選字框讓使用者選字呢?謝謝開法者們！

**Comment by kanru** [comment]
24.10 即將提供
