### ISSUE TITLE
Cmake generation failure

### ISSUE THREAD

**Issue by steven09176** [chewing/windows-chewing-tsf#140]
我試著按照所提供的procedure,    但在Cmake   的程序上無法generated
Tool Requirements 都有安裝包括
CMake >= 2.8.11
Visual Studio Express 2012 with Update 1
git
Editor with EditorConfig supported 
但這個程序無法編譯，
Visual Studio 11" -T "v110_xp" <path to windows-chewing-tsf>
    cmake -G "Visual Studio 11 Win64" -T "v110_xp" <path to windows-chewing-tsf>
請問有解嗎？

**Comment by CuteLasty** [comment]
我使用VS2017 Enterprise, 不過我想 VS2017 Community 就夠了.
Step:
1. Start a cmd.exe
2. Wwitch to C:\
3. git clone https://github.com/chewing/windows-chewing-tsf
4. cd windows-chewing-tsf
5. git submodule update --init --remote --recursive
6. Download https://www.sqlite.org/2017/sqlite-amalgamation-3200100.zip
7. Unzip it to a temp folder, then copy all unzip files to C:\windows-chewing-tsf\libchewing\thirdparty\sqlite-amalgamation  (Update sqlite3)
8. md VS2017_64
9. cmake -G "Visual Studio 15 2017 Win64" -DWITH_INTERNAL_SQLITE3=yes ..
10. cmake --build .

如此, 應該剩下 test-chewinwrapper 會fail, 這個請自己處理一下 test-chewingwrapper.cpp 裡面關於 "CHEWING_PATH" and "CHEWING_USER_PATH" 的設定...

**Comment by ShikiSuen** [comment]
看一下 git commit 歷史就很清楚了：windows xp 支援被暫時取消了。
原因是 windows xp 內建的 tsf 不完美。
