### ISSUE TITLE
是否可以 強制跳出 候選字 視窗

### ISSUE THREAD

**Issue by peter8777555** [chewing/windows-chewing-tsf#171]
雖然可以按 空格鍵 跳出 候選字 視窗.
對於從 DOS 年代就開始使用的人來說,
MS OS 以往習慣都是 強制跳出 候選字 視窗.

**Comment by kanru** [comment]
是否跟 #139 是一樣的需求？

**Comment by peter8777555** [comment]
是的.
很多人,特別是 使用數十年電腦的人,都有這種需求.

**Comment by kanru** [comment]
已於 24.10 提供
