### ISSUE TITLE
是否可以加 熱鍵 快速切換 繁簡體輸出

### ISSUE THREAD

**Issue by peter8777555** [chewing/windows-chewing-tsf#172]
希望能 用戶自定 熱鍵 快速切換 繁簡體輸出,
例如:
按一下 Ctrl+Shift+F10 簡體輸出,
按一下 Ctrl+Shift+F10 繁體輸出,
這樣就方便多了.

**Comment by peter8777555** [comment]
由於你還沒有實作這個功能,
是否能 打中文時 都去檢查 OutputSimpChinese REG 設定,
我自己寫個 批次檔 去設定 OutputSimpChinese =0 或 1

目前測試 不會立刻生效.

Notepad 打中文,
設 OutputSimpChinese=1,
打出來仍是 繁體,
需要再開另外的 Notepad 打中文 才是簡體.

**Comment by kanru** [comment]
下一版先解決偵測機碼改變的問題

**Comment by peter8777555** [comment]
感謝. 這樣就能 即時 繁/簡 切換

**Comment by peter8777555** [comment]
新酷音輸入法 (24.10.9356.43961),
更改 REG 已可以 即時 繁/簡 切換.
