### ISSUE TITLE
Windows 11 安裝失敗,無法刪除

### ISSUE THREAD

**Issue by peter8777555** [chewing/windows-chewing-tsf#173]
若有舊版,
它會先反安裝 再安裝新的,
最後安裝失敗.

看了下,
C:\Program Files (x86)\ChewingTextService\X86
C:\Program Files (x86)\ChewingTextService\X64
無法刪除.
即使先 regsvr32 /u ChewingTextService.dll 成功,
仍然無法刪除.

更新程式 很困擾.

PS:
即使按正常 反安裝 方式,
C:\Program Files (x86)\ChewingTextService\X86
C:\Program Files (x86)\ChewingTextService\X64
仍然殘留, 手動也無法刪除.

**Comment by kanru** [comment]
因為原本的 dll 還在使用中
不確定如果改用 msi 安裝能不能解決
另外一個方法是每一個版本都用不同檔名的 dll

**Comment by peter8777555** [comment]
只要能在 已有舊版 能再裝上新版 任何方法都行(不重新開機的情況下),
至於是否能移的乾淨 不是很在意,

**Comment by kanru** [comment]
請幫忙測試最新的 MSI 安裝檔

https://github.com/chewing/windows-chewing-tsf/releases/tag/nightly

**Comment by peter8777555** [comment]
於 Windows 11,
安裝 MSI 版 沒問題,
實測 X86/X64 程式 都能正常輸入中文.

1.
MSI 版 與 EXE 版 有啥不同 ?
EXE 版 仍有問題嗎 ?
我通常喜歡使用 EXE 版,
若 EXE 版 仍有問題,
請拿掉 EXE 版,免得被誤用.

2.
之前的 EXE 版
C:\Program Files (x86)\ChewingTextService\X86
C:\Program Files (x86)\ChewingTextService\X64

此 MSI 版
C:\Program Files (x86)\ChewingTextService
沒有 X86 與 X64 資料夾,
且 ChewingTextService.dll 是 X86 版,
印像中 要同時安裝 X86/X64 2 個版本 才能通用,
但實測 X86/X64 程式 都能正常輸入中文,
難道 ChewingTextService.dll 是 X86 版 通用 X86/X64 程式 ?

**Comment by kanru** [comment]
> 於 Windows 11, 安裝 MSI 版 沒問題, 實測 X86/X64 程式 都能正常輸入中文.

感謝幫忙測試！

> MSI 版 與 EXE 版 有啥不同 ? EXE 版 仍有問題嗎 ? 我通常喜歡使用 EXE 版, 若 EXE 版 仍有問題, 請拿掉 EXE 版,免得被誤用.

EXE 版目前沒有修這個問題。我是有找到可以修 EXE 的方法，可是因為之前已經決定以後要改用 MSI 了，所以就沒有花時間在 EXE 上面。MSI 測試沒有問題後就會拿掉 EXE。

MSI 比起 EXE 應該會比較容易跟其他工具整合，安裝的時候可以支援自動快照、備份等等，是比較推薦的標準格式。
 
> 之前的 EXE 版 C:\Program Files (x86)\ChewingTextService\X86 C:\Program Files (x86)\ChewingTextService\X64
> 
> 此 MSI 版 C:\Program Files (x86)\ChewingTextService 沒有 X86 與 X64 資料夾, 且 ChewingTextService.dll 是 X86 版, 印像中 要同時安裝 X86/X64 2 個版本 才能通用, 但實測 X86/X64 程式 都能正常輸入中文, 難道 ChewingTextService.dll 是 X86 版 通用 X86/X64 程式 ?

新的安裝方法依照微軟建議把 X86/X64 的 dll 分別裝到 C:\Program Files (x86)\ChewingTextService 跟 C:\Program Files\ChewingTextService，使用上跟以前沒有區別。之後還會繼續調整使用到的其他目錄位置，最後的變化會在釋出正式版的時候公告 😃

**Comment by peter8777555** [comment]
> 新的安裝方法依照微軟建議把 X86/X64 的 dll 分別裝到 C:\Program Files (x86)\ChewingTextService 跟 
> C:\Program Files\ChewingTextService，使用上跟以前沒有區別。之後還會繼續調整使用到的其他目錄
> 位置，最後的變化會在釋出正式版的時候公告 😃

原來如此,
還是有安裝 X86/X64 這 2 個程式,
難怪 我測試 X86/X64 程式 都能正常輸入中文.

題外話:
能回一下嗎 ?

是否可以 強制跳出 候選字 視窗 #171
https://github.com/chewing/windows-chewing-tsf/issues/171
看討論 有不少人有這個困擾,
有沒有考慮這個功能 ?

是否可以加 熱鍵 快速切換 繁簡體輸出 #172
https://github.com/chewing/windows-chewing-tsf/issues/172
這看您有沒有興趣,
不強求.

**Comment by kanru** [comment]
這兩個 issue 我近期有空會看一下 👍🏼

**Comment by peter8777555** [comment]
謝謝您,
這問題已解決,
我關閉這個 #173.
