### ISSUE TITLE
錯誤回報：TSF最新版本，使用倚天26鍵鍵盤在中文狀態按上方數字鍵沒有反應，必須切換到英文狀態？但舊版及PIME版均可以。

### ISSUE THREAD

**Issue by calljerryok** [chewing/windows-chewing-tsf#178]
我使用Windows Chewing TSF最新版本（2024.06.01釋出）及使用倚天26鍵於輸入中文時，由於鍵盤設置僅使用英文26個按鍵而已，無須用到數字鍵及其他符號鍵，故輸入中文狀態下，可以直接輸入數字及符號，不必切換非常方便！這裡的數字鍵是指鍵盤上方的數字鍵，不是鍵盤右側數字鍵，由於我使用69%電競短鍵盤，並沒有右側數字鍵區，合先敘明。

而今天剛安裝TSF新版，卻發現輸入中文狀態下，直接按數字鍵沒有反應，必須再按shift切換到英文狀態，按上方數字鍵才有數字輸入。
記得過去TSF舊版就可以直接使用，而且現在的PIME版也可以，在中文狀態下直接按數字鍵輸入數字，以上報告。
（備註：我電腦仍有使用PIME版，兩者同時安裝，會有影響嗎？）
感謝貴團隊無私付出，祝福您，謝謝。

**Comment by kanru** [comment]
你好，請試試看最新開發版是否解決你遇到的問題

https://github.com/chewing/windows-chewing-tsf/releases/tag/nightly

**Comment by calljerryok** [comment]
感謝您的協助，不過我使用CHROME及BING兩個瀏覽器都出現這個程式有病毒，無法完成下載，可以請教如何解決下載問題嗎?

**Comment by calljerryok** [comment]
我試著關掉防火牆來下載，也是都被擋住無法下載。

**Comment by kanru** [comment]
> 我試著關掉防火牆來下載，也是都被擋住無法下載。

瀏覽器應該有一個仍要下載的選項

這是因為開發版還沒有正式簽署安裝檔的關係

**Comment by kanru** [comment]
hmm 我剛剛測試了一下的確會被誤判為 Trojan:Script/Wacatac.B!ml
我要研究一下是怎麼回事

**Comment by kanru** [comment]
已向微軟微軟提交誤判的申訴，希望等他們處理完之後就不會有誤判的問題

現在如果你還想要測試的話，可以先暫時關閉即時保護，安裝完後再打開

![螢幕擷取畫面 2024-07-23 163218](https://github.com/user-attachments/assets/3b0b1156-a8c3-434b-a126-93e033603765)

**Comment by calljerryok** [comment]
感謝教學，暫時關掉即時防護後，我已經下載最新開發版，安裝後確實可以像舊版本直接輸入數字或符號，但新的問題又出現，就是在WORD輸入文字時，文字會變成黑塊遮擋文字無法選字，按下ENTER後才會現出文字；其次，中文狀態下按住SHIFT輸入數字鍵的標點符號出現的不是全形，只有半形，例如：數字1鍵的！會變成!，數字9鍵的（會變成(，其餘類推，因為標點符號在中文應該全形比較好看，但數字反而保持半形即可，非常感謝您的協助。

**Comment by calljerryok** [comment]
新的問題又發生——如上所述，安裝Chewing TSF最新開發版後，由於在WORD（MICROSOFT 365版本）輸入文字會被黑塊遮擋無法選字（在CHORME不會），所以我只好移除再安裝回來版本（2024.06.01釋出），結果仍然是在WORD輸入文字會被黑塊遮擋，這讓我想起之前的問題，早年我都是用Chewing TSF版，因為速度快，後來出現上面的黑塊事件後，我就改用Chewing  PIME版，但是這版本速度較慢，而且有時候在LINE輸入會非常遲鈍，所以我前幾天看到2024.06.01釋出TSF版，非常開心，但出現前面敘述的問題，有點好奇的是為何會有在WORD輸入文字會被黑塊遮擋無法選字的毛病？

**Comment by kanru** [comment]
感謝測試並回報問題，我另外開兩個 issue 追蹤

- [ ] 在WORD（MICROSOFT 365版本）輸入文字會被黑塊遮擋無法選字（在CHORME不會）
- [ ] 中文狀態下按住SHIFT輸入數字鍵的標點符號出現的不是全形，只有半形
