### ISSUE TITLE
 在WORD（MICROSOFT 365版本）輸入文字會被黑塊遮擋無法選字（在CHORME不會）

### ISSUE THREAD

**Issue by kanru** [chewing/windows-chewing-tsf#179]
新的問題又發生——如上所述，安裝Chewing TSF最新開發版後，由於在WORD（MICROSOFT 365版本）輸入文字會被黑塊遮擋無法選字（在CHORME不會），所以我只好移除再安裝回來版本（2024.06.01釋出），結果仍然是在WORD輸入文字會被黑塊遮擋，這讓我想起之前的問題，早年我都是用Chewing TSF版，因為速度快，後來出現上面的黑塊事件後，我就改用Chewing  PIME版，但是這版本速度較慢，而且有時候在LINE輸入會非常遲鈍，所以我前幾天看到2024.06.01釋出TSF版，非常開心，但出現前面敘述的問題，有點好奇的是為何會有在WORD輸入文字會被黑塊遮擋無法選字的毛病？

_Originally posted by @calljerryok in https://github.com/chewing/windows-chewing-tsf/issues/178#issuecomment-2244938905_

**Comment by kanru** [comment]
@calljerryok 請問你用的是安裝版的 WORD (MICROSOFT 365)還是網頁版的？

**Comment by kanru** [comment]
如果可以的話請你提供節圖供參考

**Comment by calljerryok** [comment]
Chewing PIME版（網頁版）：不會出現在WORD輸入文字會被黑塊遮擋。
Chewing TSF早期版：在WORD輸入文字會被黑塊遮擋；後來我改用PIME版（網頁版）。
Chewing TSF（2024.06.01釋出）：這版本已經改善沒有黑塊問題，但用倚天26鍵在中文狀態，無法直接輸入數字問題（即之前反應的問題，不贅述，因為您在回覆中建議我改用下面「最新開發版」，安裝後雖然解決輸入數字問題，卻又出現黑塊問題，所以我只好移除後，改用回來Chewing TSF（2024.06.01釋出），沒辦法截圖了，只是倚天26鍵在中文狀態，無法直接輸入數字問題仍然存在。
Chewing TSF 最新開發版：https://github.com/chewing/windows-chewing-tsf/releases/tag/nightly

**Comment by calljerryok** [comment]
![螢幕擷取畫面 2024-07-29 140438](https://github.com/user-attachments/assets/3d49010a-9002-41e4-9dac-12922b816fcd)
很奇怪，這版Chewing TSF（2024.06.01釋出）在word已經改善沒有黑塊問題，但是在ppt簡報軟體卻會出現黑塊？？詳如上圖，備註：我是microsoft 365正版付費軟體。

**Comment by kanru** [comment]
感謝，提供資訊。我看看有沒有瓣法重現

**Comment by kanru** [comment]
我目前測試是沒有辦法重現，會繼續試試看

![螢幕擷取畫面 2024-07-31 090032](https://github.com/user-attachments/assets/b84edc74-9c0b-4a01-9419-973e74532559)

![螢幕擷取畫面 2024-08-01 054640](https://github.com/user-attachments/assets/80d98258-5e70-47c8-a73c-891ca92c9fb1)
