### ISSUE TITLE
使用倚天鍵輸入法時，數字按鍵沒反應

### ISSUE THREAD

**Issue by jacidtw** [chewing/windows-chewing-tsf#196]
使用倚天26鍵輸入法時，數字按鍵沒反應k
舊版的卻可以輸出成半型1234567890 
建議可以參考舊版行為。

**Comment by kanru** [comment]
請問你用的是那一個版本？
我測試用倚天26是可以直接輸出數字的

請問設定中「打字行為→模式」是什麼模式？

**Comment by jacidtw** [comment]
我是剛下載的，應該是最新版本。
我用的數字鍵是上排的1234567890沒錯。之前舊版的不用再切換成英數，在中文模式下即可直接輸出1234567890

感謝～～～至於打字行為的預設啟動模式，我都沒句選。

**Comment by kanru** [comment]
沒辦法重現，建議下載最新開發板試試
如果可以錄影或是描述如何重現（打什麼鍵）可以加速解決問題

**Comment by jacidtw** [comment]
沒錯跟 https://github.com/chewing/windows-chewing-tsf/issues/178 是同一個問題

感謝告知～

**Comment by kanru** [comment]
如果還有問題請跟我說
