### ISSUE TITLE
按下shift切換英文模式後, 先前誤輸入的注音符號沒有清空,也找不到設定可以設置, 還能繼續輸出中文, 除非ESC或手動清空, 多按好幾個鍵

### ISSUE THREAD

**Issue by ericaiei** [chewing/windows-chewing-tsf#197]
我錄了一段操作的影片, 我記得以前好像可以切換英文之後, 按下按鍵輸入的就是英文了, 不曉得是不是記錯?
在打字的時候常常不會看到下方工作列上現在是中文還是英文模式, 有時輸錯了,直接按下shift切換模式, 可是卻因為已經輸入的注音符號卡住, 要多按好幾個鍵去清空, 在按下一個字母, 非常困擾。
能否在切換中英模式時, 就清空之前尚未輸出的符號呢？

[Video_2024-10-29_191227_編輯.mp4](https://github.com/user-attachments/assets/0f605f35-6be3-40df-a86c-d35e1bae3f30)

**Comment by kanru** [comment]
謝謝回報，請問是從 Github 下載的開發版嗎？

**Comment by kanru** [comment]
看起來共分成兩個問題

1. 切換中英模式的時候沒有清楚提示
2. 切換英數模式後仍卡在注音輸入

第一點已經有計畫修正，第二點也會在近期修正，感謝回報！

**Comment by ericaiei** [comment]
抱歉, 沒即時注意到你的回覆, 感謝你
