### ISSUE TITLE
V24.10 Win+S 無法打中文

### ISSUE THREAD

**Issue by peter8777555** [chewing/windows-chewing-tsf#213]
版本:V24.10 
OS:Windows 11 23H2 22631.3672

這版的 簡單注音 測試正常.

Win+S 無法打中文

![xxx](https://github.com/user-attachments/assets/2f220462-ade2-4f3c-aa0d-8b7500ca3eaf)

**Comment by kanru** [comment]
我可以重現這個 bug

**Comment by kanru** [comment]
請幫忙測試最新開發版 https://github.com/chewing/windows-chewing-tsf/releases/tag/nightly

**Comment by peter8777555** [comment]
Windows 11 測試通過。
