### ISSUE TITLE
V24.10 特殊符號 顯示 無法讀取檔

### ISSUE THREAD

**Issue by peter8777555** [chewing/windows-chewing-tsf#215]
版本:V24.10 
OS:Windows 11 23H2 22631.3672

![xx3](https://github.com/user-attachments/assets/4f8f3867-6863-4138-82c8-2a50571ed164)

**Comment by kanru** [comment]
請問你有這兩個檔案嗎？

```
%USERPROFILE%\ChewingTextService\symbols.dat
C:\Program Files (x86)\ChewingTextService\Dictionary\symbols.dat
```

**Comment by peter8777555** [comment]
都有.

![z2](https://github.com/user-attachments/assets/69ddd63f-8040-4cdf-893a-c4c4dc3e1cb5)

**Comment by peter8777555** [comment]
題外話,
熱鍵 ` 被我其它軟體 已使用,
所以這功能對我來說 沒用.
是否能加  `  或 Scroll Lock 這 2 組 任選 ?
Scroll Lock  這鍵 通常不會用到.

**Comment by kanru** [comment]
> 題外話, 熱鍵 "1 左邊的鍵" 被我其它軟體 已使用, 所以這功能對我來說 沒用. 是否能加 "1 左邊的鍵" 或 Scroll Lock 這 2 組 任選 ? Scroll Lock 這鍵 通常不會用到.

未來計畫添加自訂快捷鍵功能

**Comment by peter8777555** [comment]
> 試試看它刪掉，或是把這個檔案複製過去能不能修復

試了 可以了,
雖然我用不到這功能.

我覺的 只需要
C:\Program Files (x86)\ChewingTextService\Dictionary\symbols.dat
這組就可以了,
不需要有又有 %USERPROFILE%\ChewingTextService\symbols.dat

**Comment by kanru** [comment]
%USERPROFILE% 內的是可以自訂的，從設定視窗修改後會另存一份，才不會修改到系統檔
我先關這個 issue
