### ISSUE TITLE
Bug 回報 中文輸入變黑方塊,  Office 2016 專業增強版 

### ISSUE THREAD

**Issue by newguest88** [chewing/windows-chewing-tsf#217]
Bug 回報 中文輸入變黑方塊,

環境: Windows 11 + Office 2016 專業增強版 (單機版)
有問題的apps: Word, PowerPoint
沒問題的app: Excel

註: PIME 輸入法 1.3.0-stable ,沒有中文輸入變黑方塊問題

Thank you!

**Comment by newguest88** [comment]
![image](https://github.com/user-attachments/assets/cd233536-f2ba-4367-8062-9096bbd9171f)

**Comment by kanru** [comment]
請幫忙測試最新開發版 https://github.com/chewing/windows-chewing-tsf/releases/tag/nightly
