### ISSUE TITLE
在WIN10內，在左下方搜尋內無法輸入中文，只能輸入英文

### ISSUE THREAD

**Issue by f000000TW** [chewing/windows-chewing-tsf#219]
在WIN10內，在左下方搜尋內無法輸入中文，只能輸入英文

應該是有BUG？   還是我的電腦有問題

**Comment by peter8777555** [comment]
這個問題 已經 回報過了

V24.10 Win+S 無法打中文 #213
https://github.com/chewing/windows-chewing-tsf/issues/213

**Comment by kanru** [comment]
請幫忙測試最新開發版 https://github.com/chewing/windows-chewing-tsf/releases/tag/nightly
