### ISSUE TITLE
Prepare release v24.10.1.0

### ISSUE THREAD

**Issue by kanru** [chewing/windows-chewing-tsf#232]
- [x] Review issues list
- [x] Make sure CHANGELOG.md is updated
- [x] Update version numbers
- [x] Update Cargo.lock
- [x] Prepare pre-release/release tarball
  ```sh
  cmake -B build
  cmake --build build -t package_source
  ```
  - [x] Verify the content of the tarball
- [x] Git tag and sign tag
- [x] Build and sign pre-built installer
- [x] Tag new release on GitHub
- [x] Update website
- [x] Send announcement

**Comment by peter8777555** [comment]
設定新酷音輸入法 (24.10.9356.43961),
與你這標題 v24.10.1
最好一致.

看是要以 
24.10.9356.43961 為準 ?
或 v24.10.1 為準 ?
或 24.10.9356.43961(v24.10.1) 為準 ?

**Comment by kanru** [comment]
> 設定新酷音輸入法 (24.10.9356.43961),
> 與你這標題 v24.10.1
> 最好一致.
> 
> 看是要以 
> 24.10.9356.43961 為準 ?
> 或 v24.10.1 為準 ?
> 或 24.10.9356.43961(v24.10.1) 為準 ?

規則是

測試版 yy.mm.9xxx.zzzzz
穩定版 yy.mm.rr0xxx.0

上個穩定版是 24.10.00315.0
下個穩定版會是 24.10.10357.0

**Comment by peter8777555** [comment]
這樣會混亂,
用戶測試 回饋版本 到底要寫哪個 ?
檔案日期 ? 
檔案大小 ? 
SHA1/SHA256 ?
新酷音輸入法 (24.10.9356.43961) ?

**Comment by kanru** [comment]
> 這樣會混亂,
> 用戶測試 回饋版本 到底要寫哪個 ?
> 檔案日期 ? 
> 檔案大小 ? 
> SHA1/SHA256 ?
> 新酷音輸入法 (24.10.9356.43961) ?
> 

寫完整版號即可 （24.10.9356.43961）
若是會混亂的話之後穩定版也都用完整版號
後面的數字不會重複所以可以簡單找到是那個時間上傳的

**Comment by kanru** [comment]
最新測試版的自動標題還要改，目前使用日期，之後改成版號

**Comment by peter8777555** [comment]
這讓你 決定,
只要能讓 使用者 準確反應 版本 都可以.
